# File: docker-compose.test.yml
# Extension: .yml
# Location: docker-compose.test.yml

version: '3.8'

services:
  # Test Database
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: cppmastery_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d cppmastery_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Test Redis
  redis-test:
    image: redis:7
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Test MongoDB
  mongodb-test:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: cppmastery_test
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test_data:/data/db

  # Backend Test Service
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://test:test123@postgres-test:5432/cppmastery_test
      REDIS_URL: redis://redis-test:6379
      MONGODB_URL: mongodb://test:test123@mongodb-test:27017/cppmastery_test
      JWT_SECRET: test-secret-key
      JWT_REFRESH_SECRET: test-refresh-secret-key
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      mongodb-test:
        condition: service_started
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  # C++ Engine Test Service
  cpp-engine-test:
    build:
      context: ./cpp-engine
      dockerfile: Dockerfile
      target: test
    environment:
      NODE_ENV: test
      BACKEND_URL: http://backend-test:8000
    ports:
      - "9001:9000"
    volumes:
      - ./cpp-engine:/app
    depends_on:
      - backend-test

  # Frontend Test Service
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: test
    environment:
      NODE_ENV: test
      NEXT_PUBLIC_API_URL: http://backend-test:8000
      NEXT_PUBLIC_CPP_ENGINE_URL: http://cpp-engine-test:9000
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend-test
      - cpp-engine-test

volumes:
  postgres_test_data:
  redis_test_data:
  mongodb_test_data:

networks:
  default:
    name: cpp-mastery-test-network