function(cppmastery_enable_coverage target)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${target} PUBLIC --coverage -O0 -g)
        target_link_options(${target} PUBLIC --coverage)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        target_compile_options(${target} PUBLIC -fprofile-instr-generate -fcoverage-mapping -O0 -g)
        target_link_options(${target} PUBLIC -fprofile-instr-generate)
    else()
        message(WARNING "Coverage instrumentation is not supported for ${CMAKE_CXX_COMPILER_ID}")
    endif()
endfunction()
