# cppmastery_enable_sanitizers(<target> "<list>") where list ⊆ {address, undefined, thread, leak, memory}
function(cppmastery_enable_sanitizers target sanitizers)
    if(NOT sanitizers)
        return()
    endif()
    if(MSVC)
        if("address" IN_LIST sanitizers)
            target_compile_options(${target} PRIVATE /fsanitize=address)
        endif()
        return()
    endif()
    if("thread" IN_LIST sanitizers AND ("address" IN_LIST sanitizers OR "leak" IN_LIST sanitizers))
        message(FATAL_ERROR "ThreadSanitizer cannot be combined with Address/LeakSanitizer")
    endif()
    string(REPLACE ";" "," joined "${sanitizers}")
    target_compile_options(${target} PUBLIC -fsanitize=${joined} -fno-omit-frame-pointer -g)
    target_link_options(${target} PUBLIC -fsanitize=${joined})
    if("undefined" IN_LIST sanitizers)
        target_compile_options(${target} PUBLIC -fno-sanitize-recover=undefined)
    endif()
endfunction()
