// Property-based tests: invariants that must hold for *every* input, checked over randomly
// generated byte strings and mutated real programs. These complement the libFuzzer harness in
// fuzz/ and run in every CI build without a fuzzing engine.

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <random>
#include <string>

#include "cppmastery/analysis/rule_engine.hpp"
#include "cppmastery/lexer/lexer.hpp"
#include "cppmastery/memory/layout.hpp"
#include "cppmastery/metrics/metrics.hpp"
#include "cppmastery/report/json_report.hpp"

using namespace cppmastery;

namespace {

void checkTokenInvariants(const SourceText& src, const std::vector<Token>& ts) {
    ASSERT_FALSE(ts.empty());
    ASSERT_EQ(ts.back().kind, TokenKind::EndOfFile);
    std::size_t cursor = 0;
    for (std::size_t i = 0; i + 1 < ts.size(); ++i) {
        const Token& t = ts[i];
        ASSERT_FALSE(t.text.empty()) << "empty token at " << t.offset;
        ASSERT_GE(t.offset, cursor) << "overlapping tokens";
        // Gap must be pure whitespace.
        for (std::size_t k = cursor; k < t.offset; ++k) {
            const char c = src.text()[k];
            ASSERT_TRUE(c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' || c == '\v')
                << "non-whitespace byte skipped at " << k;
        }
        ASSERT_LE(t.end(), src.size());
        ASSERT_EQ(src.text().substr(t.offset, t.text.size()), t.text);
        ASSERT_EQ(src.positionAt(t.offset), t.position);
        cursor = t.end();
    }
    for (std::size_t k = cursor; k < src.size(); ++k) {
        const char c = src.text()[k];
        ASSERT_TRUE(c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' || c == '\v');
    }
}

std::string randomBytes(std::mt19937& rng, std::size_t n) {
    static constexpr char kAlphabet[] =
        "abcXYZ_019 \t\n\r(){}[]<>;:,.#\"'/\\*+-=!&|^%?~@`\x01\xff\xc3\xa9";
    std::uniform_int_distribution<std::size_t> pick(0, sizeof(kAlphabet) - 2);
    std::string s;
    s.reserve(n);
    for (std::size_t i = 0; i < n; ++i) s.push_back(kAlphabet[pick(rng)]);
    return s;
}

}  // namespace

TEST(Property, LexerCoversInputExactlyOnRandomBytes) {
    std::mt19937 rng(20251003);
    std::uniform_int_distribution<std::size_t> len(0, 400);
    for (int iter = 0; iter < 2000; ++iter) {
        SourceText src(randomBytes(rng, len(rng)));
        checkTokenInvariants(src, tokenize(src));
    }
}

TEST(Property, FullPipelineIsTotalOnRandomBytes) {
    std::mt19937 rng(42);
    std::uniform_int_distribution<std::size_t> len(0, 300);
    RuleEngine engine = RuleEngine::withBuiltinRules();
    for (int iter = 0; iter < 500; ++iter) {
        SourceText src(randomBytes(rng, len(rng)));
        AnalysisReport r = engine.analyze(src);
        EXPECT_EQ(r.summary.total(), r.diagnostics.size());
        std::string json = toJson(r);
        EXPECT_FALSE(json.empty());
        TargetABI abi = TargetABI::lp64();
        (void)layoutAll(parseStructs(src), abi);
    }
}

TEST(Property, CorpusFilesAreStableUnderPrefixTruncation) {
    // Every prefix of a real program must still be analysable (editor-in-progress scenario).
    const std::filesystem::path corpus = CPPMASTERY_CORPUS_DIR;
    if (!std::filesystem::exists(corpus)) GTEST_SKIP() << "corpus not found";
    RuleEngine engine = RuleEngine::withBuiltinRules();
    std::size_t files = 0;
    for (const auto& entry : std::filesystem::recursive_directory_iterator(corpus)) {
        if (entry.path().extension() != ".cpp") continue;
        ++files;
        std::ifstream in(entry.path(), std::ios::binary);
        std::string text((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
        for (std::size_t cut = 0; cut <= text.size(); cut += 37) {
            SourceText src(text.substr(0, cut));
            checkTokenInvariants(src, tokenize(src));
            (void)engine.analyze(src);
        }
    }
    EXPECT_GT(files, 0u);
}

TEST(Property, MetricsAreDeterministic) {
    SourceText src("int f(int a){ if(a){ return 1; } return 2; }");
    const std::string a = toJson(computeMetrics(src));
    const std::string b = toJson(computeMetrics(src));
    EXPECT_EQ(a, b);
}
